name: Build/Test Angular

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        strategy:
            matrix:
                include:
                    - dockerfile: "Dockerfile"
                      folder: "angular"
                      image_name: "angular_image"
                      service_port: 8040
                      docker_port: 3000

                    - dockerfile: "Dockerfile_alpine"
                      folder: "angular"
                      image_name: "angular_alpine_image"
                      service_port: 8041
                      docker_port: 80

                    - dockerfile: "Dockerfile_alpine_nonroot"
                      folder: "angular"
                      image_name: "angular_alpine_nonroot_image"
                      service_port: 8042
                      docker_port: 80

                    - dockerfile: "Dockerfile_busybox"
                      folder: "angular"
                      image_name: "angular_busybox_image"
                      service_port: 8043
                      docker_port: 3000

                    - dockerfile: "Dockerfile_nginx"
                      folder: "angular"
                      image_name: "angular_nginx_image"
                      service_port: 8044
                      docker_port: 80

        name: Build and Test Docker Images
        uses: ./.github/workflows/buildAndTest.yml
        with:
            dockerfile: ${{ matrix.dockerfile }}
            folder: ${{ matrix.folder }}
            image_name: ${{ matrix.image_name }}
            service_port: ${{ matrix.service_port }}
            docker_port: ${{ matrix.docker_port }}